name: Gobot
on:
  workflow_call:
    inputs:
      godot-version:
        description: Godot Version
        default: '4.3'
        type: string
      environment:
        description: Pages Environment
        default: github-pages
        type: string
      delete-old-pages:
        description: Delete Old Pages
        default: 'false'
        type: string
concurrency:
  group: gobot
  cancel-in-progress: false
env:
  GODOT_VERSION: ${{ github.event.inputs.godot-version }}
jobs:
  Setup: # Analyze input to generate a dynamic build matrix, and Cache Godot and Export Templates.
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.parse.outputs.matrix }}
      modified: ${{ steps.parse.outputs.modified }}
      web: ${{ steps.parse.outputs.web }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Parse
        id: parse
        run: |
          # error if presets file missing/empty, or input malformed
          if [ ! -f export_presets.cfg ] || [ ! -s export_presets.cfg ]; then
            echo "> [!CAUTION]" >> $GITHUB_STEP_SUMMARY
            echo "> \`export_presets.cfg\` is missing or empty. Nothing to do." >> $GITHUB_STEP_SUMMARY
            exit 11
          elif ! [[ "${GODOT_VERSION}" =~ ^[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then
            echo "> [!CAUTION]" >> $GITHUB_STEP_SUMMARY
            echo "> Invalid version format: \`${GODOT_VERSION}\`." >> $GITHUB_STEP_SUMMARY
            exit 22
          fi

          # generate dynamic build matrix based on presets file
          awk_output=$(awk -F= '
          BEGIN { printf "["; first=1 }
          /^\s*platform/ { platform=$2; gsub(/^"|"$/, "", platform) }
          /^\s*export_path/ {
            path=$2; gsub(/^"|"$/, "", path)
            if (path == "") {
              path = (platform == "Linux") || (platform == "Linux/X11") ? "${{ github.event.repository.name }}.x86_64" :
                     (platform == "macOS") ? "${{ github.event.repository.name }}.zip" :
                     (platform == "Web") ? "index.html" :
                     (platform == "Windows Desktop") ? "${{ github.event.repository.name }}.exe" : ""
            }
            platform_dir = (platform == "Windows Desktop") ? "Windows" :
                           (platform == "Linux/X11") ? "Linux" : platform
            n = split(path, arr, "/")
            split(arr[n], file_parts, ".")
            printf "%s{\"target\":\"%s\",\"dir\":\"%s\",\"file\":\"%s\",\"ext\":\"%s\"}",
                   (first ? "" : ","), platform, platform_dir, file_parts[1], file_parts[2]
            first=0
          }
          END { print "]" }' export_presets.cfg)

          linux_found=$(echo "$awk_output" | jq 'any(.target == "Linux")')
          linux_x11_found=$(echo "$awk_output" | jq 'any(.target == "Linux/X11")')
          if [[ "$(echo "$awk_output" | jq 'any(.target == "Web")')" == "true" ]]; then
            echo "web=true" >> $GITHUB_OUTPUT
          fi

          # warn if version < 4.3 and Linux/X11 not found but Linux found, and make it work
          if [[ "$(printf '%s\n' "${GODOT_VERSION}" "4.3" | sort -V | head -n1)" != "4.3" && "$linux_found" == "true" && "$linux_x11_found" == "false" ]]; then
              echo "> [!NOTE]" >> $GITHUB_STEP_SUMMARY
              echo "> \`Linux\` found and \`Linux/X11\` missing. Changed to \`Linux/X11\` for Godot < 4.3." >> $GITHUB_STEP_SUMMARY
              awk_output=$(echo "$awk_output" | jq -c 'map(if .target == "Linux" then .target = "Linux/X11" else . end)')
              sed -i -e 's/name="Linux"/name="Linux\/X11"/g' -e 's/platform="Linux"/platform="Linux\/X11"/g' export_presets.cfg
              echo "modified=true" >> $GITHUB_OUTPUT
          fi

          # warn if version >= 4.3 and Linux not found but Linux/X11 found, and make it work
          if [[ "$(printf '%s\n' "${GODOT_VERSION}" "4.3" | sort -V | head -n1)" == "4.3" && "$linux_found" == "false" && "$linux_x11_found" == "true" ]]; then
              echo "> [!NOTE]" >> $GITHUB_STEP_SUMMARY
              echo "> \`Linux/X11\` found and \`Linux\` missing. Changed to \`Linux\` for Godot >= 4.3." >> $GITHUB_STEP_SUMMARY
              awk_output=$(echo "$awk_output" | jq -c 'map(if .target == "Linux/X11" then .target = "Linux" else . end)')
              sed -i -e 's/name="Linux\/X11"/name="Linux"/g' -e 's/platform="Linux\/X11"/platform="Linux"/g' export_presets.cfg
              echo "modified=true" >> $GITHUB_OUTPUT
          fi

          echo "matrix=$awk_output" >> $GITHUB_OUTPUT
      - name: Upload
        if: steps.parse.outputs.modified == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: export_presets
          path: export_presets.cfg
      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ./godot
            ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable
          key: ${{ runner.os }}_Godot_${{ env.GODOT_VERSION }}
      - name: Cache Godot
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -L -o godot.zip https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip
          unzip -q godot.zip && mv Godot_v${GODOT_VERSION}-stable_linux.x86_64 godot && chmod +x godot
          curl -L -o templates.tpz https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable && unzip -q templates.tpz && mv templates/* ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
  Build: # Export the project for each target platform concurrently.
    needs: [Setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.Setup.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Download
        if: needs.Setup.outputs.modified == 'true'
        uses: actions/download-artifact@v4
        with:
          name: export_presets
      - name: Restore
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ./godot
            ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable
          key: ${{ runner.os }}_Godot_${{ env.GODOT_VERSION }}
      - name: Import
        run: ./godot --headless --verbose --editor --quit
      - name: Export
        run: |
          mkdir -p "build/${{ matrix.dir }}"
          ./godot --headless --verbose --export-release "${{ matrix.target }}" "build/${{ matrix.dir }}/${{ matrix.file }}.${{ matrix.ext }}"
      - name: Delete
        if: needs.Setup.outputs.modified == 'true'
        uses: geekyeggo/delete-artifact@v5
        with:
          name: export_presets
      - name: Upload Web
        if: matrix.target == 'Web'
        uses: actions/upload-pages-artifact@v3
        with:
          name: ${{ github.event.repository.name }}_${{ matrix.dir }}_Godot_${{ env.GODOT_VERSION }}
          path: build/${{ matrix.dir }}
      - name: Upload Not Web
        if: matrix.target != 'Web'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_${{ matrix.dir }}_Godot_${{ env.GODOT_VERSION }}
          path: build/${{ matrix.dir }}
  Deploy: # Deploy web build to Pages after optionally deleting old Pages deployments.
    needs: [Setup, Build]
    if: needs.Setup.outputs.web == 'true'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      deployments: write
    environment:
      name: ${{ github.event.inputs.environment }}
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Delete
        if: github.event.inputs.delete-old-pages == 'true'
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: ${{ github.event.inputs.environment }}
          onlyRemoveDeployments: true
      - name: Configure
        uses: actions/configure-pages@v5
      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ${{ github.event.repository.name }}_Web_Godot_${{ env.GODOT_VERSION }}
